// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Приоритет задачи
 */
export type Priority = 'high' | 'medium' | 'low';

export type TaskStatus = 'todo' | 'in_progress' | 'done';

export type CreateTaskRequest = {
    /**
     * Название задачи
     */
    title: string;
    /**
     * Развёрнутое описание задачи
     */
    description?: string;
    priority: Priority;
};

export type Task = {
    id: string;
    title: string;
    description?: string;
    priority: Priority;
    status: TaskStatus;
    createdAt: string;
};

export type ValidationError = {
    errors: Array<FieldError>;
};

export type FieldError = {
    /**
     * Имя поля из CreateTaskRequest, к которому относится ошибка
     */
    field: string;
    /**
     * Машинный код ошибки — по нему форма выбирает текст
     */
    code: string;
    /**
     * Текст с сервера; используется как fallback, если code неизвестен
     */
    message: string;
};

export type CreateTaskData = {
    body: CreateTaskRequest;
    path?: never;
    query?: never;
    url: '/api/tasks/v1/create';
};

export type CreateTaskErrors = {
    /**
     * Ошибка валидации на сервере
     */
    422: ValidationError;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * Задача создана
     */
    201: Task;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];
