// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Приоритет задачи
 */
export const prioritySchema = z.enum([
    'high',
    'medium',
    'low'
]);

export const taskStatusSchema = z.enum([
    'todo',
    'in_progress',
    'done'
]);

export const createTaskRequestSchema = z.object({
    title: z.string().min(1).max(120),
    description: z.string().max(1000).optional(),
    priority: prioritySchema.default('medium')
});

export const taskSchema = z.object({
    id: z.uuid(),
    title: z.string(),
    description: z.string().optional(),
    priority: prioritySchema,
    status: taskStatusSchema,
    createdAt: z.iso.datetime()
});

export const fieldErrorSchema = z.object({
    field: z.string(),
    code: z.string(),
    message: z.string()
});

export const validationErrorSchema = z.object({
    errors: z.array(fieldErrorSchema)
});
